---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: base-os
description: Project GDL OS

base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: latest

modules:
  - from-file: docker.yml
  - type: files
    files:
      - source: system
        destination: /

  - from-file: libvirt.yml
  - from-file: os-release-config.yml
  - from-file: bazzite-cleanup.yml
  - from-file: input-group.yml
  - from-file: kwin-rounded-corners.yml
  - from-file: fonts-shell.yml
  - from-file: omz-shell.yml
  - from-file: yafti.yml
  - from-file: default-flatpaks.yml
  - from-file: gdl-sysexts-just.yml
  - type: initramfs
  - type: signing
